name: Deployments

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2.2.4
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.local/share/pnpm/store/v3
          key: ${{ runner.OS }}-x86-node18-pnpm7-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-x86-node18-pnpm7-${{ env.cache-name }}-
            ${{ runner.OS }}-x86-node18-pnpm7-
      - uses: actions/cache@v3
        with:
          path: |
            dist/_astro
          # astro generated images should be stored in public/ for efficient caching
          key: ${{ runner.OS }}-astro-cache-${{ hashFiles('public/**/*') }}
          restore-keys: |
            ${{ runner.OS }}-astro-cache-${{ env.cache-name }}-
            ${{ runner.OS }}-astro-cache-
      - name: Install dependencies
        run: pnpm -r i --shamefully-hoist --prefer-offline
      - name: Build
        run: pnpm build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist
      - uses: actions/deploy-pages@v2
        id: deployment
      - name: 'Post-deplotyment: Logging'
        run: echo "Deployed at ${{ steps.deployment.outputs.page_url }}"
